In [1]:
Ind = ['3_1', '4_1', '5_1', '5_2']

import numpy as np

In [2]:
#reading kymo data
Nbeads = 100
conf = 100000
replicas = 10
data = []

kymodata = np.zeros((len(Ind), replicas*conf, Nbeads))
#Random
for i in range(len(Ind)):
    for rep in range(replicas):
        file1 = "D:\PoL\Beads100\\0_5\Localisation\KNOT"+str(i+1)+"\BU__KN_KNOT"+str(Ind[i])+str(rep) + ".dat"
        print(file1)
        f=open(file1,"r")
        lines=f.readlines()[3:] # skip 3 lines of header
        start=[]
        end=[]
        length=[]
        #check if BU_KNOT file is complete
        if (len(lines)<5):
            continue
        for x in lines:
            start.append(int(x.split(' ')[3]))
            end.append(int(x.split(' ')[4]))
            length.append(int(x.split(' ')[5]))
        f.close()

        #ring is circular, need to take into account both ends
        for j in range(conf):
            for k in range(Nbeads):
                if (start[j]>end[j]):
                    if ((k>=start[j]) or (k<=end[j])):
                        kymodata[i][j+(conf*rep)][k] = 1
                elif (start[j]<end[j]):
                    if ((k>=start[j]) and (k<=end[j])):
                        kymodata[i][j+(conf*rep)][k] = 1
                        
kymodata


D:\PoL\Beads100\0_5\Localisation\KNOT1\BU__KN_KNOT3_10.dat
D:\PoL\Beads100\0_5\Localisation\KNOT1\BU__KN_KNOT3_11.dat
D:\PoL\Beads100\0_5\Localisation\KNOT1\BU__KN_KNOT3_12.dat
D:\PoL\Beads100\0_5\Localisation\KNOT1\BU__KN_KNOT3_13.dat
D:\PoL\Beads100\0_5\Localisation\KNOT1\BU__KN_KNOT3_14.dat
D:\PoL\Beads100\0_5\Localisation\KNOT1\BU__KN_KNOT3_15.dat
D:\PoL\Beads100\0_5\Localisation\KNOT1\BU__KN_KNOT3_16.dat
D:\PoL\Beads100\0_5\Localisation\KNOT1\BU__KN_KNOT3_17.dat
D:\PoL\Beads100\0_5\Localisation\KNOT1\BU__KN_KNOT3_18.dat
D:\PoL\Beads100\0_5\Localisation\KNOT1\BU__KN_KNOT3_19.dat
D:\PoL\Beads100\0_5\Localisation\KNOT2\BU__KN_KNOT4_10.dat
D:\PoL\Beads100\0_5\Localisation\KNOT2\BU__KN_KNOT4_11.dat
D:\PoL\Beads100\0_5\Localisation\KNOT2\BU__KN_KNOT4_12.dat
D:\PoL\Beads100\0_5\Localisation\KNOT2\BU__KN_KNOT4_13.dat
D:\PoL\Beads100\0_5\Localisation\KNOT2\BU__KN_KNOT4_14.dat
D:\PoL\Beads100\0_5\Localisation\KNOT2\BU__KN_KNOT4_15.dat
D:\PoL\Beads100\0_5\Localisation\KNOT2\BU__KN_KNOT4_16.d

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 0., 0., 1.]]])

In [5]:
kymodata = kymodata.astype(int)

In [34]:
np.save('kymodata.npy', kymodata)

In [11]:
kymodata[0,10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
data = np.load('D:\PoL\Beads100\kymodata.npy')

In [39]:
data[1][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])